=== cmu-db/benchbase/config/db/database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="database" type="databaseType"/>
    <xs:complexType name="databaseType">
        <xs:all>
            <xs:element type="xs:string" name="type">
                <xs:annotation>
                    <xs:documentation>the Database Type as specified in com.oltpbenchmark.types.DatabaseType</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="COCKROACHDB"/>
                        <xs:enumeration value="MARIADB"/>
                        <xs:enumeration value="MYSQL"/>
                        <xs:enumeration value="NOISEPAGE"/>
                        <xs:enumeration value="PHOENIX"/>
                        <xs:enumeration value="POSTGRES"/>
                        <xs:enumeration value="SPANNER"/>
                        <xs:enumeration value="HSQLDB"/>
                        <xs:enumeration value="SQLSERVER"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="driverClass">
                <xs:annotation>
                    <xs:documentation>the fully qualified class name of the JDBC Driver class</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="url">
                <xs:annotation>
                    <xs:documentation>the properly formatted JDBC url</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="username" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>the database username</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="password" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>the database password</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="transactionIsolation" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>the Transaction Isolation level as specified in com.oltpbenchmark.api.config.TransactionIsolation</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="TRANSACTION_SERIALIZABLE"/>
                        <xs:enumeration value="TRANSACTION_READ_COMMITTED"/>
                        <xs:enumeration value="TRANSACTION_REPEATABLE_READ"/>
                        <xs:enumeration value="TRANSACTION_READ_UNCOMMITTED"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:int" name="batchSize" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>the batch size</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:int" name="retries" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>the number of times to retryable transactions will be retried before failing</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>

</xs:schema>

=== cmu-db/benchbase/config/db/hsqldb.xml
<?xml version="1.0" encoding="utf-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="database.xsd">
    <type>HSQLDB</type>
    <driverClass>org.hsqldb.jdbc.JDBCDriver</driverClass>
    <url>jdbc:hsqldb:mem:benchbase;sql.syntax_mys=true</url>
    <username>admin</username>
    <password>password</password>
    <transactionIsolation>TRANSACTION_SERIALIZABLE</transactionIsolation>
    <batchSize>128</batchSize>
    <retries>3</retries>
</database>
