=== cmu-db/benchbase/config/dialect/dialect.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="dialect" type="dialectType"/>
    <xs:complexType name="statementType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required">
                    <xs:annotation>
                        <xs:documentation>the name of the instance of com.oltpbenchmark.api.SQLStmt on owning Procedure</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="statementsType">
        <xs:sequence>
            <xs:element type="statementType" name="statement" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>overrides the value for of the sql statement with the given "name" on the owning Procedure</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="procedureType">
        <xs:sequence>
            <xs:element type="statementsType" name="statements">
                <xs:annotation>
                    <xs:documentation>the instances of com.oltpbenchmark.api.SQLStmt that exist on this com.oltpbenchmark.api.Procedure</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="procedureClass" use="required">
            <xs:annotation>
                <xs:documentation>the fully qualified class name of the com.oltpbenchmark.api.Procedure implementation</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="proceduresType">
        <xs:sequence>
            <xs:element type="procedureType" name="procedure" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>an instances of com.oltpbenchmark.api.Procedure</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dialectType">
        <xs:sequence>
            <xs:element type="proceduresType" name="procedures">
                <xs:annotation>
                    <xs:documentation>the instances of com.oltpbenchmark.api.Procedure that define this workload</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="type"/>
    </xs:complexType>
</xs:schema>

=== cmu-db/benchbase/config/dialect/tpcc.sqlserver.xml
<?xml version="1.0" encoding="utf-8"?>
<dialect xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="SQLSERVER" xsi:noNamespaceSchemaLocation="dialect.xsd">
    <procedures>
        <procedure name="Delivery">
            <statements>
                <statement name="delivGetOrderIdSQL">
                    SELECT TOP 1 NO_O_ID
                    FROM NEW_ORDER
                    WHERE NO_D_ID = ? AND NO_W_ID = ? ORDER BY NO_O_ID ASC
                </statement>
            </statements>
        </procedure>
        <procedure name="NewOrder">
            <statements>
                <statement name="stmtGetDistSQL">
                    SELECT D_NEXT_O_ID,D_TAX
                    FROM DISTRICT
                    WHERE D_W_ID = ? AND D_ID = ?
                </statement>
                <statement name="stmtGetStockSQL">
                    SELECT S_QUANTITY, S_DATA, S_DIST_01, S_DIST_02, S_DIST_03, S_DIST_04, S_DIST_05,
                    S_DIST_06, S_DIST_07, S_DIST_08, S_DIST_09, S_DIST_10
                    FROM STOCK
                    WHERE S_I_ID = ? AND S_W_ID = ?
                </statement>
            </statements>
        </procedure>
        <procedure name="OrderStatus">
            <statements>
                <statement name="ordStatGetNewestOrdSQL">
                    SELECT TOP 1 O_ID, O_CARRIER_ID, O_ENTRY_D
                    FROM OORDER
                    WHERE O_W_ID = ? AND O_D_ID = ? AND O_C_ID = ? ORDER BY O_ID DESC
                </statement>
            </statements>
        </procedure>
    </procedures>
</dialect>

=== cmu-db/benchbase/config/dialect/resourcestresser.hsqldb.xml
<?xml version="1.0" encoding="utf-8"?>
<dialect xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="HSQLDB" xsi:noNamespaceSchemaLocation="dialect.xsd">
    <procedures>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.resourcestresser.procedures.CPU1">
            <statements>
                <statement name="cpuSelect">
                    <![CDATA[SELECT count(*) FROM (SELECT concat(concat(concat(concat(concat(passwd,?),?),?),?),?) FROM cputable WHERE empid >= 0 AND empid < 100) AS T1]]>
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.resourcestresser.procedures.CPU2">
            <statements>
                <statement name="cpuSelect">
                    <![CDATA[SELECT count(*) FROM (SELECT concat(concat(concat(concat(concat(passwd,?),?),?),?),?) FROM cputable WHERE empid >= 0 AND empid < 100) AS T2]]>
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.resourcestresser.procedures.Contention1">
            <statements>
                <statement name="lockSleep">
                    select 1 from locktable where empid = ?
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.resourcestresser.procedures.Contention2">
            <statements>
                <statement name="lockSleep">
                    select 1 from locktable where empid = ?
                </statement>
            </statements>
        </procedure>
    </procedures>
</dialect>

=== cmu-db/benchbase/config/dialect/epinions.oracle.xml
<?xml version="1.0" encoding="utf-8"?>
<dialect xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="ORACLE" xsi:noNamespaceSchemaLocation="dialect.xsd">
    <procedures>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.GetAverageRatingByTrustedUser">
            <statements>
                <statement name="getAverageRating">
                    SELECT avg(rating) FROM "review" r, "trust" t WHERE r.u_id=t.target_u_id AND r.i_id=? AND t.source_u_id=?
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.GetItemAverageRating">
            <statements>
                <statement name="getAverageRating">
                    SELECT avg(rating) FROM "review" r WHERE r.i_id=?
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.GetItemReviewsByTrustedUser">
            <statements>
                <statement name="getReview">
                    SELECT * FROM "review" r WHERE r.i_id=?
                </statement>
                <statement name="getTrust">
                    SELECT * FROM "trust" t WHERE t.source_u_id=?
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.GetReviewItemById">
            <statements>
                <statement name="getReviewItem">
                    SELECT * FROM "review" r, "item" i WHERE i.i_id = r.i_id and r.i_id=? AND ROWNUM &lt;= 10
                    ORDER BY rating
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.GetReviewsByUser">
            <statements>
                <statement name="getReviewUser">
                    SELECT * FROM "review" r, "useracct" u WHERE u.u_id = r.u_id AND r.u_id=? AND ROWNUM &lt;= 10
                    ORDER BY rating
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.UpdateItemTitle">
            <statements>
                <statement name="updateItem">
                    UPDATE "item" SET title = ? WHERE i_id=?
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.UpdateReviewRating">
            <statements>
                <statement name="updateReview">
                    UPDATE "review" SET rating = ? WHERE i_id=? AND u_id=?
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.UpdateTrustRating">
            <statements>
                <statement name="updateTrust">
                    UPDATE "trust" SET trust = ? WHERE source_u_id=? AND target_u_id=?
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.UpdateUserName">
            <statements>
                <statement name="updateUser">
                    UPDATE "useracct" SET name = ? WHERE u_id=?
                </statement>
            </statements>
        </procedure>
    </procedures>
</dialect>

=== cmu-db/benchbase/config/dialect/ycsb.spanner.xml
<?xml version="1.0" encoding="utf-8"?>
<dialect xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="SPANNER" xsi:noNamespaceSchemaLocation="dialect.xsd">
    <procedures>
        <procedure name="ReadModifyWriteRecord">
            <statements>
                <statement name="selectStmt">
                    SELECT * FROM usertable WHERE ycsb_key=?
                </statement>
            </statements>
        </procedure>
        <procedure name="InsertRecord">
            <statements>
                <statement name="insertStmt">
                    INSERT INTO usertable (ycsb_key, field1, field2, field3, field4, field5, field6, field7, field8, field9, field10) VALUES (?,?,?,?,?,?,?,?,?,?,?)
                </statement>
            </statements>
        </procedure>
    </procedures>
</dialect>

=== cmu-db/benchbase/config/dialect/epinions.sqlserver.xml
<?xml version="1.0" encoding="utf-8"?>
<dialect xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="SQLSERVER" xsi:noNamespaceSchemaLocation="dialect.xsd">
    <procedures>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.GetReviewItemById">
            <statements>
                <statement name="getReviewItem">
                    SELECT TOP 10 * FROM review r, item i WHERE i.i_id = r.i_id and r.i_id=?
                    ORDER BY rating;
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.GetReviewsByUser">
            <statements>
                <statement name="getReviewUser">
                    SELECT TOP 10 * FROM review r, [useracct] u WHERE u.u_id = r.u_id AND r.u_id=?
                    ORDER BY rating;
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.epinions.procedures.UpdateUserName">
            <statements>
                <statement name="updateUser">
                    UPDATE [useracct] SET name = ? WHERE u_id=?;
                </statement>
            </statements>
        </procedure>
    </procedures>
</dialect>

=== cmu-db/benchbase/config/dialect/twitter.postgres.xml
<?xml version="1.0" encoding="utf-8"?>
<dialect xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="POSTGRES" xsi:noNamespaceSchemaLocation="dialect.xsd">
    <procedures>
        <procedure name="GetTweet">
            <statements>
                <statement name="getTweet">
                    SELECT * FROM "tweets" WHERE id = ?
                </statement>
            </statements>
        </procedure>
        <procedure name="GetTweetsFromFollowing">
            <statements>
                <statement name="getFollowing">
                    SELECT f2 FROM "follows" WHERE f1 = ? LIMIT 20
                </statement>
                <statement name="getTweets">
                    SELECT * FROM "tweets" WHERE uid IN (??)
                </statement>
            </statements>
        </procedure>
        <procedure name="GetFollowers">
            <statements>
                <statement name="getFollowers">
                    SELECT f2 FROM "followers" WHERE f1 = ? LIMIT 20
                </statement>
                <statement name="getFollowerNames">
                    SELECT uid, name FROM "user_profiles" WHERE uid IN (??)
                </statement>
            </statements>
        </procedure>
        <procedure name="GetUserTweets">
            <statements>
                <statement name="getTweets">
                    SELECT * FROM "tweets" WHERE uid = ? LIMIT 10
                </statement>
            </statements>
        </procedure>
        <procedure name="InsertTweet">
            <statements>
                <statement name="insertTweet">
                    INSERT INTO "added_tweets" VALUES (default, ?, ?, ?)
                </statement>
            </statements>
        </procedure>
    </procedures>
</dialect>

=== cmu-db/benchbase/config/dialect/tpch.postgres.xml
<?xml version="1.0" encoding="utf-8"?>
<dialect xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="POSTGRES" xsi:noNamespaceSchemaLocation="dialect.xsd">
    <procedures>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q1">
            <statements>
                <statement name="query_stmt">
                    select l_returnflag, l_linestatus, sum(l_quantity) as sum_qty, sum(l_extendedprice) as sum_base_price, sum(l_extendedprice * (1 - l_discount)) as sum_disc_price, sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge, avg(l_quantity) as avg_qty, avg(l_extendedprice) as avg_price, avg(l_discount) as avg_disc, count(*) as count_order from lineitem where l_shipdate &lt;= date '1998-12-01' - concat(?,' day')::interval group by l_returnflag, l_linestatus order by
                    l_returnflag, l_linestatus
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q3">
            <statements>
                <statement name="query_stmt">
                    select l_orderkey, sum(l_extendedprice * (1 - l_discount)) as revenue, o_orderdate, o_shippriority from customer, orders, lineitem where c_mktsegment = ? and c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate &lt; ?::date and l_shipdate > ?::date group by l_orderkey, o_orderdate, o_shippriority order by revenue desc, o_orderdate limit 10
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q4">
            <statements>
                <statement name="query_stmt">
                    select o_orderpriority, count(*) as order_count from orders where o_orderdate >= ?::date and o_orderdate &lt; ?::date + interval '3' month and exists ( select * from lineitem where l_orderkey = o_orderkey and l_commitdate &lt; l_receiptdate ) group by o_orderpriority order by o_orderpriority
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q5">
            <statements>
                <statement name="query_stmt">
                    select n_name, sum(l_extendedprice * (1 - l_discount)) as revenue from customer, orders, lineitem, supplier, nation, region where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = ? and o_orderdate >= ?::date and o_orderdate &lt; ?::date + interval '1' year group by n_name order by revenue desc;
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q6">
            <statements>
                <statement name="query_stmt">
                    select sum(l_extendedprice * l_discount) as revenue from lineitem where l_shipdate >= ?::date and l_shipdate &lt; ?::date + interval '1' year and l_discount between ?::decimal - 0.01 and ?::decimal + 0.01 and l_quantity &lt; ?
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q10">
            <statements>
                <statement name="query_stmt">
                    select c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer, orders, lineitem, nation where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= ?::date and o_orderdate &lt; ?::date + interval '3' month and l_returnflag = 'R' and c_nationkey = n_nationkey group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc limit 20
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q12">
            <statements>
                <statement name="query_stmt">
                    select l_shipmode, sum(case when o_orderpriority = '1-URGENT' or o_orderpriority = '2-HIGH' then 1 else 0 end) as high_line_count, sum(case when o_orderpriority &lt;> '1-URGENT' and o_orderpriority &lt;> '2-HIGH' then 1 else 0 end) as low_line_count from orders, lineitem where o_orderkey = l_orderkey and l_shipmode in (?, ?) and l_commitdate &lt; l_receiptdate and l_shipdate &lt; l_commitdate and l_receiptdate >= ?::date and l_receiptdate &lt; ?::date + interval '1' year
                    group by
                    l_shipmode order by l_shipmode
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q14">
            <statements>
                <statement name="query_stmt">
                    select 100.00 * sum(case when p_type like 'PROMO%' then l_extendedprice * (1 - l_discount) else 0 end) / sum(l_extendedprice * (1 - l_discount)) as promo_revenue from lineitem, part where l_partkey = p_partkey and l_shipdate >= ?::date and l_shipdate &lt; ?::date + interval '1' month
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q15">
            <statements>
                <statement name="createview_stmt">
                    create view revenue0 (supplier_no, total_revenue) as select l_suppkey, sum(l_extendedprice * (1 - l_discount)) from lineitem where l_shipdate >= ?::date and l_shipdate &lt; ?::date + interval '3' month group by l_suppkey
                </statement>
            </statements>
        </procedure>

        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q20">
            <statements>
                <statement name="query_stmt">
                    select s_name, s_address from supplier, nation where s_suppkey in ( select ps_suppkey from partsupp where ps_partkey in ( select p_partkey from part where p_name like ? ) and ps_availqty > ( select 0.5 * sum(l_quantity) from lineitem where l_partkey = ps_partkey and l_suppkey = ps_suppkey and l_shipdate >= ?::date and l_shipdate &lt; ?::date + interval '1' year ) ) and s_nationkey = n_nationkey and n_name = ? order by s_name
                </statement>
            </statements>
        </procedure>
        <procedure procedureClass="com.oltpbenchmark.benchmarks.tpch.procedures.Q22">
            <statements>
                <statement name="query_stmt">
                    select cntrycode, count(*) as numcust, sum(c_acctbal) as totacctbal from ( select substring(c_phone from 1 for 2) as cntrycode, c_acctbal from customer where substring(c_phone from 1 for 2) in (?, ?, ?, ?, ?, ?, ?) and c_acctbal > ( select avg(c_acctbal) from customer where c_acctbal > 0.00 and substring(c_phone from 1 for 2) in (?, ?, ?, ?, ?, ?, ?) ) and not exists ( select * from orders where o_custkey = c_custkey ) ) as custsale group by cntrycode order by cntrycode
                </statement>
            </statements>
        </procedure>
    </procedures>
</dialect>

=== cmu-db/benchbase/config/dialect/wikipedia.sqlserver.xml
<?xml version="1.0" encoding="utf-8"?>
<dialect xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="SQLSERVER" xsi:noNamespaceSchemaLocation="dialect.xsd">
    <procedures>
        <procedure name="AddWatchList">
            <statements>
                <statement name="insertWatchList">
                    INSERT INTO [watchlist] (wl_user,wl_namespace,wl_title,wl_notificationtimestamp) VALUES (?,?,?,NULL)
                </statement>
                <statement name="setUserTouched">
                    UPDATE [useracct] SET user_touched = ? WHERE user_id = ?
                </statement>
            </statements>
        </procedure>
        <procedure name="RemoveWatchList">
            <statements>
                <statement name="removeWatchList">
                    DELETE FROM [watchlist] WHERE wl_user = ? AND wl_namespace = ? AND wl_title = ?
                </statement>
                <statement name="setUserTouched">
                    UPDATE [useracct] SET user_touched = ? WHERE user_id = ?
                </statement>
            </statements>
        </procedure>
        <procedure name="GetPageAnonymous">
            <statements>
                <statement name="selectPage">
                    SELECT TOP 1 * FROM page WHERE page_namespace = ? AND page_title = ?
                </statement>
                <statement name="selectPageRevision">
                    SELECT TOP 1 * FROM page,revision WHERE (page_id=rev_page) AND rev_page = ? AND page_id = ? AND (rev_id=page_latest)
                </statement>
                <statement name="selectText">
                    SELECT TOP 1 old_text,old_flags FROM text WHERE old_id = ?
                </statement>
            </statements>
        </procedure>
        <procedure name="UpdatePage">
            <statements>
                <statement name="selectUser">
                    SELECT * FROM [useracct] WHERE user_id = ?
                </statement>
                <statement name="updateUserEdit">
                    UPDATE [useracct] SET user_editcount=user_editcount+1 WHERE user_id = ?
                </statement>
                <statement name="updateUserTouched">
                    UPDATE [useracct] SET user_touched = ? WHERE user_id = ?
                </statement>
            </statements>
        </procedure>
        <procedure name="GetPageAuthenticated">
            <statements>
                <statement name="selectUser">
                    SELECT TOP 1 * FROM [useracct] WHERE user_id = ?
                </statement>
                <statement name="selectPage">
                    SELECT TOP 1 * FROM page WHERE page_namespace = ? AND page_title = ?
                </statement>
                <statement name="selectPageRevision">
                    SELECT TOP 1 * FROM page, revision WHERE (page_id=rev_page) AND rev_page = ? AND page_id = ? AND (rev_id=page_latest)
                </statement>
                <statement name="selectText">
                    SELECT TOP 1 old_text,old_flags FROM text WHERE old_id = ?
                </statement>
            </statements>
        </procedure>
    </procedures>
</dialect>
